version: "3.9"
services:
  hub:
    build: example-services/hub
    ports:
      - "6000:6000"
    environment:
      FIZZER_PORT: 6001
      BUZZER_PORT: 6002
  fizzer:
    build: example-services/fizzer
  buzzer:
    build: example-services/buzzer
  jaeger:
    image: jaegertracing/all-in-one:1.42.0
    profiles:
      - tracing
    ports:
      # UI
      - "16686:16686"
    environment:
      COLLECTOR_OTLP_ENABLED: true
      LOG_LEVEL: info
